[package]
name = "ri1-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
